apiVersion: v1
kind: Service
metadata:
  name: nginx6
  namespace: nginx-ingress6
spec:
  type: LoadBalancer
  loadBalancerIP: '130.211.130.121'
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx6
